_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_test:
    path:     /test/{page}
    defaults: { _controller: AcmeDemoBundle:Test:index, page:1 }
    requirements:
          page: \d+

_test_view:
    path: /test/view/{name}
    defaults: { _controller: AcmeDemoBundle:Test:view }
    requirements:
          name:  \w+


_book:
    path: /books/
    defaults: { _controller: AcmeDemoBundle:Book:index }

_book_create:
    path: /book/create
    defaults: { _controller: AcmeDemoBundle:Book:create }

_book_view:
    path: /book/view/{id}
    defaults: { _controller: AcmeDemoBundle:Book:view }
    requirements:
      id:  \d+

_book_update:
    path: /book/update
    defaults: { _controller: AcmeDemoBundle:Book:update }

_book_delete:
    path: /book/delete
    defaults: { _controller: AcmeDemoBundle:Book:delete }